# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='user',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
