# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160515_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='foto',
            field=models.ImageField(blank=True, default='img/none.png', null=True, upload_to='img/users/'),
        ),
    ]
