# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='foto',
            field=models.ImageField(upload_to='img/users/'),
        ),
    ]
