# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prioridad', models.CharField(max_length=45)),
                ('color_prioridad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_role', models.CharField(max_length=45)),
            ],
        ),
    ]
