# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prioridad', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='Estado',
            new_name='Tipo_estado',
        ),
    ]
