# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_role', models.CharField(max_length=45)),
            ],
        ),
    ]
