# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_documento_tipo_documento'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_documento',
        ),
    ]
