# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20160517_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Proyecto')),
            ],
        ),
        migrations.RenameModel(
            old_name='Project_role',
            new_name='Role',
        ),
        migrations.AddField(
            model_name='roles_project',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Role'),
        ),
        migrations.AddField(
            model_name='roles_project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
