# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160522_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles_project',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tipo_role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
