# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160812_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tipo_estado'),
        ),
    ]
