# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20160522_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles_project',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Proyecto'),
        ),
        migrations.AlterField(
            model_name='roles_project',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Tipo_role'),
        ),
        migrations.AlterField(
            model_name='roles_project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
