# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario_tarea',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
