# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160517_2301'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='user',
            field=models.ManyToManyField(to='project.Proyecto'),
        ),
    ]
