# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_comentario_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo_documento',
        ),
    ]
