# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tarea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='user',
            field=models.ManyToManyField(to='project.Roles_project'),
        ),
    ]
