# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20160522_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='user',
            new_name='integrant',
        ),
    ]
