# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20160628_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion_tarea',
            field=models.CharField(max_length=300),
        ),
    ]
