# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20160522_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tipo_prioridad'),
        ),
        migrations.DeleteModel(
            name='Tipo_prioridad',
        ),
    ]
