# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160522_2144'),
        ('task', '0005_auto_20160522_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='project.Proyecto'),
            preserve_default=False,
        ),
    ]
