# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160522_2144'),
        ('task', '0006_tarea_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_integrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Roles_project')),
            ],
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='integrant',
        ),
        migrations.AddField(
            model_name='tarea_integrantes',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Tarea'),
        ),
    ]
