# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20160731_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='icon',
            field=models.CharField(default='fa-tasks', max_length=20),
        ),
    ]
