# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationuser_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='link_notificacion',
        ),
        migrations.RemoveField(
            model_name='notificationuser',
            name='visto',
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='titulo_notificacion',
            field=models.CharField(max_length=200),
        ),
    ]
