# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20160807_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='titulo_notificacion',
            field=models.CharField(max_length=500),
        ),
    ]
