# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion_actividad',
            field=models.CharField(max_length=300),
        ),
    ]
